package com.your.package.name // Make sure to update this to your actual package name

import android.content.Context
import android.util.Base64
import javax.crypto.SecretKey
import com.your.package.name.R // Make sure to import your project's R class

/**
 * Manages the encryption and decryption for a single, secure client-server exchange.
 * An instance of this class should be used for one request/response cycle.
 *
 * **IMPORTANT USAGE NOTE FOR ANDROID VIEWMODELS:**
 * This class is stateful (it stores the `sessionAesKey` internally). To ensure the key
 * is not lost during configuration changes (like screen rotation), you should create and
 * manage an instance of this class within a component that survives such changes,
 * like an Android `ViewModel`.
 *
 * Example ViewModel Usage:
 * ```
 * class LoginViewModel(private val appContext: Application) : AndroidViewModel(appContext) {
 * // Hold the manager instance as a property in the ViewModel
 * private var secureExchange: SecureExchangeManager? = null
 *
 * fun performLogin(userDataJson: String) {
 * viewModelScope.launch {
 * // Create a new instance for this specific login attempt
 * secureExchange = SecureExchangeManager(appContext)
 * val requestBody = secureExchange!!.encryptRequest(userDataJson)
 *
 * // ... make network call with requestBody ...
 * // val response = repository.login(requestBody)
 *
 * // ... on success, decrypt the response using the same instance ...
 * // val decryptedData = secureExchange!!.decryptResponse(response.data)
 * }
 * }
 * }
 * ```
 *
 * @param context The Android context, needed to access string resources.
 */
class SecureExchangeManager(private val context: Context) {

    // This will hold the unique AES key for this specific request/response cycle.
    private var sessionAesKey: SecretKey? = null

    /**
     * Encrypts a plaintext string, preparing it for sending to the server.
     * This method generates and internally stores a new session key.
     *
     * @param plaintextContent The raw string data (e.g., a JSON object) to encrypt.
     * @return A JSON string containing the encrypted key and data, ready to be sent as the request body.
     */
    fun encryptRequest(plaintextContent: String): String {
        val serverRsaPublicKey = getPublicKey()
        val plaintextBytes = plaintextContent.toByteArray(Charsets.UTF_8)

        // Generate a new AES key for this exchange and store it
        val aesKey = EncryptionHelper.generateAesKey()
        this.sessionAesKey = aesKey

        // Encrypt the payload with the AES key
        val encryptedDataBytes = EncryptionHelper.encrypt(plaintextBytes, aesKey)
        val encryptedDataBase64 = Base64.encodeToString(encryptedDataBytes, Base64.NO_WRAP)

        // Encrypt the AES key with the server's public RSA key
        val wrappedAesKeyBase64 = EncryptionHelper.wrapAesKey(aesKey, serverRsaPublicKey)

        // Format the final JSON body for the request
        return """
        {
          "key": "$wrappedAesKeyBase64",
          "data": "$encryptedDataBase64"
        }
        """
    }

    /**
     * Decrypts an encrypted response from the server.
     * This method relies on the session key generated by the `encryptRequest` call.
     *
     * @param encryptedResponse The Base64 encoded 'data' field from the server's JSON response.
     * @return The decrypted plaintext string.
     * @throws IllegalStateException if `encryptRequest` was not called first.
     */
    fun decryptResponse(encryptedResponse: String): String {
        // Retrieve the session key that was stored when the request was encrypted
        val key = sessionAesKey ?: throw IllegalStateException("encryptRequest must be called before decryptResponse.")

        val encryptedResponseBytes = Base64.decode(encryptedResponse, Base64.DEFAULT)
        val decryptedResponseBytes = EncryptionHelper.decrypt(encryptedResponseBytes, key)
        return String(decryptedResponseBytes, Charsets.UTF_8)
    }

    /**
     * Retrieves the server's public key from strings.xml.
     */
    private fun getPublicKey(): String {
        return context.getString(R.string.server_public_key)
    }
}
